plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.ksp
    id("kotlinx-serialization")
}


android {
    namespace 'com.core.data'
    compileSdk 34

    defaultConfig {
        minSdk 34
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"

        Properties properties = new Properties()
        properties.load(project.rootProject.file("local.properties").newDataInputStream())

        buildConfigField "String", "ALCHEMY_API", "\"${properties.getProperty("ALCHEMY_API")}\""
        buildConfigField "String", "TOKEN_PRICE_API", "\"${properties.getProperty("TOKEN_PRICE_API","fallback_value")}\""






    }

    buildFeatures {
        buildConfig = true // <--- Enable BuildConfig generation in a library module
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation project(path: ':core:database')
    implementation project(path: ':core:model')
    implementation project(path: ':core:common')
    implementation project(path: ':core:datastore')
    implementation project(path: ':uniswap-routing-sdk')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    implementation 'com.squareup.moshi:moshi-kotlin:1.13.0'
    implementation 'com.squareup.retrofit2:converter-moshi:2.9.0'

    implementation libs.ethos.wallet
    implementation libs.web3j.android
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    implementation libs.moshi
    implementation libs.kotlinx.datetime

    implementation libs.fasterxml
    implementation libs.headlong

    // ENS resolving
    implementation 'com.github.komputing.kethereum:ens:0.85.7'
    implementation 'com.github.komputing.kethereum:rpc:0.85.7'
    implementation 'com.github.komputing.kethereum:model:0.85.7'

    implementation(libs.androidx.tracing.ktx)
    implementation(libs.kotlinx.serialization.json)



}