plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'

    alias libs.plugins.ksp
    alias libs.plugins.hilt.android
    alias libs.plugins.google.protobuf
}

android {
    namespace 'com.core.datastore'
    compileSdk 34

    defaultConfig {
        minSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

// protobuf-protoc

/*
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.0"

        generateProtoTasks {
            all().forEach { task ->
                task.builtins {
                    create("java") {
                        option("lite")
                    }
                }
            }
        }
    }
}
 */

protobuf {
    protoc {
        artifact = libs.protobuf.protoc.get().toString()
    }
    generateProtoTasks {
        all().forEach { task ->
            task.builtins {
                java {
                    option("lite")
                }
                kotlin {
                    option("lite")
                }
            }
        }
    }
}



androidComponents {
    onVariants(selector().all()) { variant ->
        // No need for afterEvaluate in many cases,
        // but if you truly need it, keep it.
        afterEvaluate {
            def capName = variant.name.capitalize()

            tasks.named("ksp${capName}Kotlin",
                    org.jetbrains.kotlin.gradle.tasks.KotlinCompile)
                    .configure { kspTask ->
                        // Link the proto generation outputs:
                        source(tasks.named("generate${capName}Proto").get().outputs)
                        // or setSource(...) if you prefer:
                        // setSource(tasks.named("generate${capName}Proto").get().outputs)
                    }
        }
    }
}

ksp {
    arg("allowDependentSymbolResolution", "true")
}

dependencies {

    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation project(path: ':core:model')

    implementation libs.androidx.datastore.preferences
    implementation libs.androidx.datastore.proto
    implementation libs.hilt.android
    ksp libs.hilt.compiler
    implementation libs.protobuf.kotlin.lite

}